import {
  faLongArrowAltRight,
  faUser,
  faPhoneAlt,
  faAt,
  faLock,
  faKey,
  faHome,
  faPlusSquare,
  faUserCircle,
  faSearch,
  faUpload,
  faTh,
  faUserFriends,
  faGlobeAmericas,
  faTimes,
  faChevronCircleDown,
  faSignOutAlt,
  faEdit,
  faPencilAlt
} from "@fortawesome/free-solid-svg-icons";

export const fontAwesomeIcons = {
  faLongArrowAltRight,
  faUser,
  faPhoneAlt,
  faAt,
  faLock,
  faKey,
  faHome,
  faPlusSquare,
  faUserCircle,
  faSearch,
  faUpload,
  faTh,
  faUserFriends,
  faGlobeAmericas,
  faTimes,
  faChevronCircleDown,
  faSignOutAlt,
  faEdit,
  faPencilAlt
}